name: master Build Matrix

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_ubuntu_20:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: jurplel/install-qt-action@v2
    - name: make
      run: make
  build_ubuntu_18:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: jurplel/install-qt-action@v2
    - name: make
      run: make
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jurplel/install-qt-action@v2
      - name: vcvars
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cd build
          qmake ../src/kristall.pro
          nmake release
          cd release
          mt.exe -manifest Hello.exe.manifest -outputresource:Hello.exe
